### PR TITLE
Push plugin does not work on Android with NativeScript 2.3

### PR DESCRIPTION
**Pull request by manojdcoder**
Issue #12 
- Updated gradle for Google Play services 9.0.1: Fixes a class change compilation error with ContextCompat.getNoBackupFilesDir()
- Added required permissions for 9.0.1

### CODE REVIEW

**Comment by AntonDobrev** [comment]
@manojdcoder Thank you very much for your contribution - it really helped resolve the run-time issue. However, we decided to go with referencing the latest available version of the Google Play Services SDK on the server (using _+_). Also, can you please specify why is the _ACCESS_NETWORK_STATE_ PERMISSION required? I am not sure if this is needed for the logic to work out of the box. 

I will close this PR for now because I already submitted one with changing the gradle dependency with _+_.

**Comment by manojdcoder** [comment]
@AntonDobrev I'm not really sure why GCM requires`ACCESS_NETWORK_STATE` permission but without that it throws a run time permission error.
